language: node_js
node_js:
  - "8"
script:
  - npm run eslint
  - npm run test-cov

before_install:
  - export NODE_ENV=developent

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
